version: '3'
services:
  herse_database:
    image: postgres:13.3-alpine
    container_name: herse_database
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_HOST: ${POSTGRES_HOST}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - herse_data:/var/lib/postgresql/data

volumes:
  herse_data:
